config/routes.rb
Rails.application.routes.draw do

  resources :gifts do
    get :luck, on: :member
    get :reset, on: :member
  end
  resources :users

end

app/models/gift.rb
class Gift < ActiveRecord::Base
  has_many :user_gifts
  has_many :users, through: :user_gifts


end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :user_gifts
  has_many :gifts, through: :user_gifts


  def xxx
    puts 'ddd'
  end



end

app/models/user_gift.rb
class UserGift < ActiveRecord::Base
  belongs_to :user
  belongs_to :gift

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  before_action :set_gift, only: [:show, :edit, :update, :destroy]


  def index
    @gifts = Gift.all

    user_ids = UserGift.all.pluck(:user_id)
    @users = User.where.not(id: user_ids)
  end


  def reset
    @gift = Gift.find params[:id]

    @gift.users.clear

    redirect_to gifts_url
  end

  def luck
    @gift = Gift.find params[:id]

    # if @gift.name == '杯子'
    #   user_ids = UserGift.includes(:gift).where(gifts: {name: ['杯子']}).pluck(:user_id)
    #   @users = User.where.not(id: user_ids).where(role: 'student')
    # end

    user_ids = UserGift.pluck(:user_id)
    @users = User.where.not(id: user_ids)


    if @gift.amount > @gift.users.count
      @gift.users << @users.sample
    else
      flash[:error] = "奖品不够咯"
    end

    redirect_to gifts_path
  end

  # GET /gifts/new
  def new
    @gift = Gift.new
  end

  # GET /gifts/1/edit
  def edit
  end

  # POST /gifts
  # POST /gifts.json
  def create
    @gift = Gift.new(gift_params)

    respond_to do |format|
      if @gift.save
        format.html { redirect_to gifts_url, notice: 'Gift was successfully created.' }
        format.json { render :show, status: :created, location: @gift }
      else
        format.html { render :new }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gifts/1
  # PATCH/PUT /gifts/1.json
  def update
    respond_to do |format|
      if @gift.update(gift_params)
        format.html { redirect_to gifts_url, notice: 'Gift was successfully updated.' }
        format.json { render :show, status: :ok, location: @gift }
      else
        format.html { render :edit }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifts/1
  # DELETE /gifts/1.json
  def destroy
    @gift.destroy
    respond_to do |format|
      format.html { redirect_to gifts_url, notice: 'Gift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gift
      @gift = Gift.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gift_params
      params[:gift].permit(:grade, :name, :amount)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user].permit(:name, :role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def alert_type(type)
    if type == 'notice'
      'ui info message container'
    else
      'ui negative message container'
    end
  end

end

app/views/gifts/_form.html.erb
<%= default_form_for(@gift) do |f| %>

  <%= f.text_field :grade %>
  <%= f.text_field :name %>
  <%= f.number_field :amount %>
  <%= f.submit %>

<% end %>

app/views/gifts/edit.html.erb
<h1>Editing Gift</h1>

<%= render 'form' %>

<%= link_to 'Show', @gift %> |
<%= link_to 'Back', gifts_path %>

app/views/gifts/index.html.erb
<h1 class="ui header">奖品列表</h1>

<table class="ui table">
  <thead>
    <tr>
      <th>奖品类别</th>
      <th>奖品名称</th>
      <th>数量</th>
      <th class="six wide column">中奖人</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @gifts.each do |gift| %>
      <tr>
        <td><%= gift.grade %></td>
        <td><%= gift.name if gift.users.count > 0 %></td>
        <td><%= gift.amount %></td>
        <td><%= gift.users.pluck(:name).join(',') %></td>
        <td><%= link_to '抽奖', luck_gift_path(gift) %></td>
        <td><%= link_to '重置', reset_gift_path(gift) %></td>
        <td><%= link_to '编辑', edit_gift_path(gift) %></td>
        <td><%= link_to '删除', gift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="ui segment">
  <% @users.each do |user| %>
    <span class="ui grey"><%= user.name %></span>
  <% end %>
</div>

app/views/gifts/new.html.erb
<div class="twelve wide column">

  <ul class="ui breadcrumb">
    <li class="section"><%= link_to '抽奖列表', gifts_path %></li>
    <li class="divider"> / </li>
    <li class="section">New Gift</li>
  </ul>

  <%= render 'form' %>

</div>

app/views/layouts/_navbar.html.erb
<div class="ui borderless menu">
  <div class="ui container">


    <%= image_tag "logo.png", class: 'item', size: '50x50' %>
    <div class="header ui red item">
      Rails Girls
    </div>

    <%= link_to '抽奖', gifts_path, class: 'item' %>
    <%= link_to '人员列表', users_path, class: 'item' %>


  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Game</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>
<%= render 'shared/alert' %>

<div class="ui grid container">
  <%= yield %>
</div>

</body>
</html>

app/views/shared/_alert.html.erb
<% flash.each do |type, msg| %>
  <div class="<%= alert_type(type) %>">
    <i class="close icon"></i>
    <p><%= msg %></p>
  </div>
<% end %>

<script>
  $('.message .close').on('click', function() {
    $(this).closest('.message').fadeOut();
  });
</script>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
<div class="alert alert-block alert-error">
  <a class="close" data-dismiss='alert' href="#">×</a>
  <p><strong>有 <%= target.errors.count %> 处问题导至无法提交:</strong></p>
  <ul>
    <% target.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/users/_form.html.erb
<%= default_form_for(@user) do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :role %>
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'New User', new_user_path %>

<h2>人数： <%= User.count %> </h2>

<table class="ui celled table">
  <thead>
    <tr>
      <th>ID</th>
      <th>姓名</th>
      <th>角色</th>
      <th>操作</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>